name: 'heroku-set-env-vars'

inputs:
    app:
        required: true
        description: |
            Heroku app.
            Ex: 'app'.

    env-vars:
        required: true

    token:
        required: true
        description: |
            Heroku API Key.
            Ex: 'asdf1234'.

runs:
    using: 'composite'

    steps:
        - name: 'Set env vars'
          uses: 'intercapinc/heroku-client@48a0127c4f9227b043d3af78fdaa997be701382e'
          with:
              endpoint: 'apps/${{ inputs.app }}/config-vars'
              method: 'PATCH'
              token: '${{ inputs.token }}'
              expected: 200
              data: '${{ inputs.env-vars }}'
